name: Test Build Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Run daily at midnight
  workflow_dispatch:
  push:
    tags:
      - 'v1'
      - 'v1-test'
    paths:
      - 'action.yml'
      - '.github/workflows/test-build-workflow.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'action.yml'
      - '.github/workflows/test-build-workflow.yml'

jobs:
  test-coverage-build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-latest
            target: i686-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            use-cross: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            use-cross: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            use-cross: false
          - os: windows-latest
            target: i686-pc-windows-msvc
            use-cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            use-cross: false
          - os: macos-13 # Intel
            target: x86_64-apple-darwin
            use-cross: false
          - os: macos-14 # M1/M2 (aarch64)
            target: aarch64-apple-darwin
            use-cross: false
          - os: ubuntu-latest
            target: x86_64-pc-windows-gnu
            use-cross: true
            label: '[Wine] x86_64-pc-windows-gnu'
          - os: ubuntu-latest
            target: i686-pc-windows-gnu
            use-cross: true
            label: '[Wine] i686-pc-windows-gnu'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: Sewer56/prs-rs
          ref: d08599ed5473616f57d57a0966939e1a5dbda9b4
      - name: Test Coverage Build
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1-test
        with:
          rust-toolchain: stable
          target: ${{ matrix.target }}
          use-cross: ${{ matrix.use-cross }}
          features: 'c-exports,std'
          no-default-features: true
          additional-test-args: '--ignored --test-threads=1'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  test-nightly-beta-build:
    strategy:
      matrix:
        rust-toolchain: [nightly, beta]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: Sewer56/prs-rs
          ref: d08599ed5473616f57d57a0966939e1a5dbda9b4
      - name: Test Nightly/Beta Build
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1-test
        with:
          rust-toolchain: ${{ matrix.rust-toolchain }}
          target: x86_64-unknown-linux-gnu
          features: 'c-exports,std'
          no-default-features: true
          additional-test-args: '--ignored --test-threads=1'
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  test-skipping-rust-install:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            rust-toolchain: stable
            target: x86_64-unknown-linux-gnu
          - os: windows-latest
            rust-toolchain: stable
            target: x86_64-pc-windows-msvc
          - os: macos-13 # Intel
            rust-toolchain: stable
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: Sewer56/prs-rs
          ref: d08599ed5473616f57d57a0966939e1a5dbda9b4
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.target }}
      - name: Test Skipping Rust Install
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1-test
        with:
          rust-toolchain: ${{ matrix.rust-toolchain }}
          target: ${{ matrix.target }}
          install-rust-toolchain: false
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  test-skipping-rust-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: Sewer56/prs-rs
          ref: d08599ed5473616f57d57a0966939e1a5dbda9b4
      - name: Test Skipping Rust Cache
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1-test
        with:
          setup-rust-cache: false
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  test-skipping-coverage-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Test Repository
        uses: actions/checkout@v4
        with:
          repository: Sewer56/prs-rs
          ref: d08599ed5473616f57d57a0966939e1a5dbda9b4
      - name: Test Skipping Coverage Upload
        uses: Reloaded-Project/devops-rust-test-and-coverage@v1-test
        with:
          upload-coverage: false
          codecov-token: ${{ secrets.CODECOV_TOKEN }}